[package]
name = "brusque"
version = "0.1.0"
authors = ["Maciej Goszczycki <mgoszcz2@gmail.com>"]

[dependencies]
pest = "0.4.1"
docopt = "0.8.0"
num = { version = "0.1.39", default-features = false, features = ["bigint"] }

[profile.release]
lto = true
panic = "abort"
